e_fort/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^spools/', include('spools.urls', namespace="spools")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('spools.urls', namespace="spools")),
)

spools/urls.py
from django.conf.urls import patterns, url

from spools import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
)

spools/models.py
from django.db import models

class SidebarItem(models.Model):
    content = models.CharField(max_length=200)
    position = models.IntegerField(default=0, unique=True)

    def __unicode__(self):
        return self.content


class Thumper(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.CharField(blank=True, max_length=200)
    content = models.TextField(blank=True)
    image = models.ImageField(blank=True, upload_to='images')
    votes = models.IntegerField(default=0)
    parent = models.IntegerField(null=True)

    def __unicode__(self):
        return self.content

    def is_valid(self):
        return not (not self.content and not self.image)

tents/models.py
from django.db import models

class Spool(models.Model):
    subject = models.CharField(blank=True, max_length=200)

    def __unicode__(self):
        return self.subject


class Thumper(models.Model):
    spool = models.ForeignKey(Spool)
    created_at = models.DateTimeField(auto_now_add=True)
    author_text = models.CharField(blank=True, max_length=200)
    content_text = models.CharField(blank=True, max_length=2000)
    image = models.ImageField(blank=True, upload_to='images')
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.content_text

spools/forms.py
from django import forms

from .models import Thumper

class ThumperForm(forms.ModelForm):
    class Meta:
        model = Thumper
        fields = ['author', 'content', 'image']

    def clean(self):
        cleaned_data = super(ThumperForm, self).clean()
        if (not cleaned_data['content'] and not cleaned_data['image']):
            raise forms.ValidationError("Form has no content.")
        return cleaned_data

spools/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils import timezone
from django.views import generic
from django.views.generic.edit import CreateView

from .models import SidebarItem, Thumper
from .forms import ThumperForm

class DetailView(generic.DetailView):
    model = Thumper
    template_name = 'spools/thumper_detail.html'


class IndexView(generic.ListView):
    template_name = 'spools/thumper_index.html'
    context_object_name = 'latest_thumper_list'

    def dispatch(self, request, *args, **kwargs):
        if request.method == "POST":
            thumper_form = ThumperForm(request.POST)
            if thumper_form.is_valid():
                new_thumper = thumper_form.save()

            return HttpResponseRedirect(request.path)

        return super(IndexView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['form'] = ThumperForm()
        context['sidebar_items_list'] = SidebarItem.objects.order_by('-position')
        return context

    def get_queryset(self):
        """
        Return the last 10 thumpers.
        """
        return Thumper.objects.order_by('-created_at')[:10]

spools/templates/spools/_sidebar.html
<ul>
  {% for item in sidebar_items_list %}
  <li>{{ item.content|safe }}</li>
  {% endfor %}
</ul>

spools/templates/spools/_thumper.html
{% if thumper.content %}
<div class="content">{{ thumper.content }}</div>
{% endif %}

{% if thumper.image %}
<img src="{{ thumper.image }}" />
{% endif %}

{% if thumper.author %}
<div class="author">{{ thumper.author }}</div>
{% endif %}

spools/templates/spools/base.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}E{% endblock %}</title>

  {% load staticfiles %}

  <link rel="stylesheet" type="text/css" href="{% static 'spools/style.css' %}" />
</head>
<body>

  {% if sidebar_items_list %}
  <div id="sidebar">
    {% include "spools/_sidebar.html" %}
  </div>
  {% endif %}

  <div id="content">
    {% block content %}{% endblock %}
  </div>

</body>
</html>

spools/templates/spools/index.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}E{% endblock %}</title>

  {% load staticfiles %}

  <link rel="stylesheet" type="text/css" href="{% static 'spools/style.css' %}" />
</head>
<body>
  <div id="sidebar">
    {% block sidebar %}
    <ul>
      <li><a href="/">Home</a></li>
      <li><a style="font-size:200%;" href="{% url 'spools:index' %}">S</a></li>
      <li><a style="font-size:300%;" href="/mix/">?</a></li>
    </ul>
    {% endblock %}
  </div>
  <div id="content">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

spools/templates/spools/sidebar.html
<ul>
  {% for item in sidebar_items_list %}
  <li>{{ item.content|safe }}</li>
  {% endfor %}
</ul>

spools/templates/spools/spool_detail.html
{% extends "spools/base.html" %}

{% block content %}
<h1>{{ spool.subject }}</h1>
{% endblock %}

spools/templates/spools/thumper_detail.html
{% extends "spools/base.html" %}

{% block content %}
  {% include "spools/_thumper.html" %}
{% endblock %}

spools/templates/spools/thumper_form.html
<form action="" method="post"
  {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Post" />
</form>

spools/templates/spools/thumper_index.html
{% extends "spools/base.html" %}

{% block content %}
<div class="new-thumper">
  {% include "spools/thumper_form.html" %}
</div>

{% if latest_thumper_list %}
<ul>
  {% for thumper in latest_thumper_list %}
  <li>
    {% include "spools/_thumper.html" %}

    <a href="{% url 'spools:detail' thumper.id %}">{{ thumper.id }}</a>
  </li>
  <hr />
  {% endfor %}
</ul>
{% else %}
<p>No thumpers.</p>
{% endif %}
{% endblock %}

spools/templates/spools/thumper_widget.html
{% if thumper.content %}
<div class="content">{{ thumper.content }}</div>
{% endif %}

{% if thumper.image %}
<img src="{{ thumper.image }}" />
{% endif %}

{% if thumper.author %}
<div class="author">{{ thumper.author }}</div>
{% endif %}